server.port=8081
#CREATE DATABASE church_app_db;
#CREATE USER church_user WITH PASSWORD 'church_password';
#GRANT ALL PRIVILEGES ON DATABASE church_db TO church_user;
#ALTER DATABASE church_db OWNER TO church_user;

spring.datasource.url=jdbc:postgresql://localhost:5432/church_app_db
spring.datasource.username=church_user
spring.datasource.password=church_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT settings (use a strong secret: 32+ chars)
app.security.jwt.secret=change-this-to-a-very-long-secret-key
app.security.jwt.access-ttl-minutes=15
app.security.jwt.refresh-ttl-days=7
app.security.bootstrap.enabled=false

# Rate limiting
app.rate-limit.capacity=100
app.rate-limit.refill-per-minute=10
app.rate-limit.login.capacity=10
app.rate-limit.login.refill-per-minute=5
