ALTER TABLE persons ADD COLUMN IF NOT EXISTS first_name VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE persons ADD COLUMN IF NOT EXISTS last_name VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE persons ADD COLUMN IF NOT EXISTS image_url VARCHAR(1024);
